### PR TITLE
Renaming from gammasim-tools to simtools

### PR DESCRIPTION
**Pull request by GernotMaier**
Addresses issue https://github.com/gammasim/gammasim-tools/issues/466

(and yes, the branch name is a bit misleading)

### CODE REVIEW

**Comment by orelgueta** [comment]
I assume this PR is unnecessary and should be deleted?

**Comment by GernotMaier** [comment]
@orelgueta  - this one is good - it includes the changes to the github action workflows. Please review (after the checks are completed)

**Review by orelgueta — APPROVED** [review]
Looks good and tests are almost all passed. Approving and you can merge when everything passed.

**Comment by GernotMaier** [comment]
I manual stopped and restarted the checks so that all the changes in simtools are taken into account here.

**Comment by orelgueta** [comment]
All checks have passed so maybe now we can merge it?

**Pull request merged**
